service: LambdaPythong
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    #fileName: requirements-prod.txt
    #dockerSsh: true
    #dockerFile: ./path/to/Dockerfile
    #dockerBuildCmdExtraArgs: ["--build-arg", "MY_GREAT_ARG=123"]
    #dockerRunCmdExtraArgs: ["-v", "${env:PWD}:/my-app"]
    #noDeploy:
    #  - pytest


functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          path: sky-data
          method: any


